### ISSUE TITLE
Adding documentation for most properties in settings

### ISSUE THREAD

**Issue by HugoGiraudel** [zurb/motion-ui#24]
Most maps from settings are not completely documented: https://github.com/zurb/motion-ui/blob/master/src/_settings.scss.

**Comment by gakimball** [comment]
Good catch, I'll address it this week.

**Comment by gakimball** [comment]
*Actually*, looking at it again I remembered why they aren't documented. These maps are meant to be user-editable, which means you can not only change values, but also add or remove them. Because of that I wasn't sure if it was worth documenting every property, because there's no need to explain each individual item.

Using `$motion-ui-speeds` as an example, the map-level documentation explains what the map does, so as long as your SassDoc implementation prints out the values of the map, the user can see what's going on.

```scss
/// Default speed that transitions and animations play at, along with values for modifier classes to change the speed.
/// @type Map
$motion-ui-speeds: (
  default: 500ms,
  slow: 750ms,
  fast: 250ms,
) !default;
```

Two of the maps, `$motion-ui-classes` and `$motion-ui-settings`, have a fixed number of values, which is why each item is documented individually.

**Comment by HugoGiraudel** [comment]
Makes sense I suppose.
