### ISSUE TITLE
-webkit -and -ms-prefix for classes

### ISSUE THREAD

**Issue by codemonkey1988** [zurb/motion-ui#54]
Hi,

I just want to know, if there is a reason why the -webkit and -ms prefixes got deleted? 
We got some information from customers with iOS 8 devices where the CSS transitions does not work. That's because Safari 8 only support transitions with the -webkit-prefix.
Same thing for IE9 with -ms-prefix.

**Comment by gakimball** [comment]
Looking at the [most recent CSS build](https://github.com/zurb/motion-ui/blob/master/dist/motion-ui.css), the `-webkit-` prefixes are still there. In what context are you not seeing them? If you're not using one of our starter templates, which include [Autoprefixer](https://github.com/postcss/autoprefixer), you'll need to add Autoprefixer yourself.

As for `-ms-`, it was removed because IE9 doesn't support transforms, and IE10 supports them unprefixed. That means `-ms-` would only be needed to prefix `transition` properties, but there's nothing for IE9 to transition, making the added CSS unnecessary. Motion UI is more or less incompatible with IE9 because all of Motion UI's effects are all built with transforms.

**Comment by codemonkey1988** [comment]
Hi, thanks for your response. I include the motion-ui.scss and generate the css with grunt. As I am newly to grunt and npm, I did not know the autoprefixer yet.
Thank you for this hint and please accept my apology. This makes my live easier :)

**Comment by gakimball** [comment]
@codemonkey1988 Once you learn how Autoprefixer works, it's *amazing*. You just tell it what browsers you support and it does the rest. You'll never write a prefix again!
